version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run:
          name: Set PYTHONPATH
          command: echo "export PYTHONPATH=\"$PYTHONPATH:$(pwd)\"" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pytest --verbose -s
workflows:
  version: 2
  test_workflow:
    jobs:
      - test